06 components
js-tasks-ru/vue-20231109_vadim40 pull request #5
Opened 2023-12-26 18:00 UTC by Vatson76

2023-12-26 18:01 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-26 18:06 UTC, Vatson76 commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Кажется, тут что-то не так. Но только с этим у меня тесты заработали и инпуты. хотя все равно дата в инпутах ломается. В общем, идея такая. реализовал свой v-model с пробросом не target.value а target.valueAsNumber, однако сломался UiInput и без v-model не хотел выводить даты. Если оставить только v-model без переписи @input, то в set приходит строчка и тогда не работает вообще ничего))

2023-12-27 19:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-27 21:17 UTC, ShGKme requested changes
Требуются небольшие исправления в 
- `06-wrappers/03-UiInput`
- `06-wrappers/06-UiInputDate`

2023-12-27 21:17 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
>      </div>
Здесь любая иконка выводится как левая иконка перед инпутом.

2023-12-27 21:17 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> -      <img class="icon" alt="icon" />
Блок с иконкой после инпута - удалился

2023-12-27 21:17 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +  <component :is="tag" :type="componentType" :class="['button', 'button_' + variant, {'button_block': block}]">
Статические классы, которые всегда есть у элемента, можно описывать явно в шаблоне через обычный атрибут `class="class-name"`. Так будет видно и основные классы верстки, и какие классы определяются динамически + не потребуется оборачивать в массив, если элемента только два.

Уточняю, так как в этом PR это встречается почти в каждой задаче.

2023-12-27 21:17 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +      <span v-show="shownImage" class="image-uploader__text">Удалить изображение</span>
Здесь всегда выводится три элемента с разным текстом, хотя два из них и скрыты визуально.

Лучше выводить один и динамически вычислять, какой в нём текст. Это будет и лучше для производительности, и не будет дублирования разметки.

2023-12-27 21:17 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Здесь `formattedModelValue` меняется сразу в двух местах. Так как `v-model` - это синтаксический сахар для двух других директив, этот код эквивалентен следующему:
```html
 <UiInput
      :type="type"
      :step="step"
      :value="formattedModelValue"
      @input="formattedModelValue = ($event.target.valueAsNumber)"
      @update:model-value="formattedModelValue = $event"
      :model-value="formattedModelValue"
      v-bind="$attrs"
/>
```

То есть `formattedModelValue = <значение>` выполняется два раза, причём с разными значениями.

Это некорректно, если значение обрабатывается вручную через `@input`, то `v-model` уже не должен использоваться. Вместо него здесь можно просто передать параметр `model-value`, не обрабатывая событие обновления модели.

2023-12-28 09:43 UTC, Vatson76 commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Понял, спасибо

2023-12-28 10:16 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-28 12:07 UTC, ShGKme requested changes

2023-12-28 12:07 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Теперь `formattedModelValue` обновляется в трёх местах:
1. `@input="formattedModelValue = `
2. `@update:model-value="formattedModelValue = $event"`
3. `v-model="formattedModelValue"` (включает в себя `@update:model-value="formattedModelValue = $event"`)

Свойство должно обновляться только один раз.

Требуется убрать обработку события обновления модели (оно не нужно, так как обработка идёт через событие `input`) и директиву `v-model` (так как она не только передаёт значение модели, но и также обрабатывает событие обновления модели).

`v-model` - просто сахар для обычного параметра и события. Параметр модели можно привязывать и без `v-model`, как обычный параметр.

2023-12-28 17:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-28 17:25 UTC, Vatson76 commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Но тогда я не могу получить в formattedModelValue в set число, а не строку. Если я оставляю только v-model, то     event.target.valueAsNumber === undefined в коде  set(event) {
        this.$emit('update:modelValue', event.target.valueAsNumber)
      },

2023-12-28 19:09 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Как и писал выше, `v-model` не нужно оставлять, он вообще не должен использоваться, если значение получается другим образом. Вместо `v-model` нужно только передать значение модели

2023-12-29 07:43 UTC, Vatson76 commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +      <UiInput :multiline="field.name === 'description'" :name="field.name" v-model="localAgendaItem[field.model]"/>
После того, как я таким образом связал v-model, сломались тесты с полями. Хотя все работает и ивенты порождаются, не подскажите в чем проблема?

2023-12-29 07:43 UTC, Vatson76 commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +      deep: true,
Так же не проходят тесты на смену времени, хотя на самой форме все работает и время меняется как надо в обе стороны. Тоже не очень понимаю почему и в чем проблема

2023-12-29 07:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-29 07:59 UTC, Vatson76 commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Запустался уже)) Убрал v-model. Оставил только value и @input. Время теперь не обновляется. Оно обновляется только когда я использую v-model

2023-12-29 09:15 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Нельзя передавать `value`. Такого параметра у `UiInput` нет. И он не пробрасывается как атрибут.

`UiInput` определяет значение через значение модели и передавать нужно именно значение модели - `modelValue`

2023-12-29 09:15 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Напомню, что `v-model` - это сахар для двух действий. Лишь одно из них здесь было лишним.

2023-12-29 10:59 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Здесь в вычисляемом свойстве создаётся копия пропса. Но вычисляемые свойства — только для чтения, и мутировать их значение — нельзя.

Хотя само вычисляемое свойство такое допустимо, его нельзя использовать как локальное состояние компонента, изменять его в элементах формы или мутировать в `watch`.

Поэтому такое вычисляемое свойство — не нужно. Можно работать напрямую с `localAgendaItem`

2023-12-29 10:59 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +        this.$emit('update:agendaItem', {...newVal});
Здесь с событием передаётся не локальное состояние, а значение в `clonedLocalAgendaItem`.

Сам watch во время своей работы меняет именно локальное состояние. `newValue` от `clonedLocalAgendaItem` будет получен с актуальным значением, когда `watch` сработает повторно из-за перевычисления `computed` и получения в нём уже нового значения.

2023-12-29 11:02 UTC, Vatson76 commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      v-model="formattedModelValue"
Заработало! Спасибо!

2023-12-29 11:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-29 11:07 UTC, Vatson76 commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Когда я работал напрямую с localAgendaItem у меня newValue и oldValue были одинаковыми, в них ничего не менялось, я вычитал, что это из-за deep: true. И нашел такое решение, оно заработало и разница появилась. Я так же пробовал dequal на localAgendaItem и agendaItem, но опять же не сработало

2023-12-29 11:09 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    }
Здесь не совсем корректно генерируется порядок элементов форм.

При попадании в первое условие, первое условие для `title` поля совсем пропадает, а не заменяется.

Затем оно добавляется в `else` в конце, но добавляется `push`-ем в конец, в итоге заголовок - последний, а не первый.

2023-12-29 11:10 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Да, действительно, если клонировать, то будет корректный `oldValue` и `newValue`. Это проглядел.

2023-12-29 11:11 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Тогда так можно работать.

2023-12-29 11:12 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Альтернативно, раз тут работать нужно лишь с `startsAt` полем, то и следить можно только за ним отдельным `watch`:

```js
watch: {
  'localAgendaItem.startsAt'(newStartsAt, oldStartAt) {}
}
```

2023-12-29 11:14 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    }
Тоже с полями доклада.

2023-12-29 11:18 UTC, Vatson76 commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
А они не будут тригерить друг друга? Т.к в 'localAgendaItem.startsAt' будет меняться 'localAgendaItem.endsAt' и это изменение поймает watch, который следит за всем localAgendaItem

2023-12-29 13:59 UTC, Vatson76 commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Добавил localAgendaItem.startsAt. На форме все по прежнему работает как надо, а вот тесты не проходят(

2023-12-29 13:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-29 14:59 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Хм, локально у меня проходят

2023-12-29 15:03 UTC, ShGKme requested changes

2023-12-29 15:03 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +          this.localAgendaItem.endsAt = newEndsAt.toLocaleString().substring(12, 17);
`input` ожидает дату строго в формате `HH:MM` в 24ч, а `toLocaleString` возвращает строку в разном формате в зависимости от настроек браузера. Например, `12/29/2023, 4:01:14 PM`.

`toISOString()` тут тоже не подойдёт, так как сейчас дата вычисляется в локальном часовом поясе, а `toISO` вернёт в UTC.

Нужно либо здесь вручную собирать время, либо указывать конкретную локализацию, либо использовать `toISOString()`, но в `new Date` добавить полное время (секунды, миллисекунды) и `Z` как часовой пояс.

2024-01-01 17:03 UTC, Vatson76 commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +          this.localAgendaItem.endsAt = newEndsAt.toLocaleString().substring(12, 17);
Исправил, спасибо

2024-01-01 17:04 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-01-02 18:39 UTC, ShGKme approved these changes

2024-01-02 18:41 UTC, merged